name: E2E tests of latest release

on:
  push:
    branches:
      - release-*

permissions:
  checks: write

jobs:
  check:
    name: Run script
    runs-on: ubuntu-latest
    outputs:
      run-e2e-tests: ${{ steps.run.outputs.RUN_E2E_TESTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Run script
        id: run
        run: |
          echo "--- latestReleaseBranch"
          latestReleaseBranch="$(git branch -r --list 'origin/release-*' | sort --version-sort | tail -n 1 | tr -d ' ')"
          echo "$latestReleaseBranch"
          echo "---"

          echo "--- current branch"
          echo "origin/${{ github.ref_name }}"
          echo "---"

          if [ "$latestReleaseBranch" != "origin/${{ github.ref_name }}" ]; then
            echo "older branch - nothing to do"
            echo "RUN_E2E_TESTS=false" >> $GITHUB_OUTPUT
          else
            echo "changes on current release branch - run e2e"
            echo "RUN_E2E_TESTS=true" >> $GITHUB_OUTPUT
          fi
          exit 0

  run-in-k8s:
    name: Run in Kubernetes latest
    needs: [check]
    #environment: E2E
    runs-on:
      - ubuntu-latest
      #- self-hosted
      #- operator-e2e
    if: ${{ needs.check.outputs.run-e2e-tests == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run e2e test
        run: |
          echo "--- run-in-k8s"
      #  uses: ./.github/actions/run-e2e
      #  with:
      #    flc-namespace: dto-daily
      #    flc-environment: dto-k8s-latest-flc
      #    target-branch: ${{ github.ref_name }}
      #    tenant1-name: ${{ secrets.TENANT1_NAME }}
      #    tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
      #    tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
      #    tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
      #    tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
      #    tenant2-name: ${{ secrets.TENANT2_NAME }}
      #    tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
      #    github-token: ${{ secrets.GITHUB_TOKEN }}

  run-in-ocp:
    name: Run in OpenShift latest
    needs: [check]
    #environment: E2E
    runs-on:
      - ubuntu-latest
      #- self-hosted
      #- operator-e2e
    if: ${{ needs.check.outputs.run-e2e-tests == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run e2e test
        run: |
          echo "--- run-in-ocp"
      #  uses: ./.github/actions/run-e2e
      #  with:
      #    flc-namespace: dto-daily
      #    flc-environment: dto-ocp-latest-flc
      #    target-branch: ${{ github.ref_name }}
      #    tenant1-name: ${{ secrets.TENANT1_NAME }}
      #    tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
      #    tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
      #    tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
      #    tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
      #    tenant2-name: ${{ secrets.TENANT2_NAME }}
      #    tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
      #    github-token: ${{ secrets.GITHUB_TOKEN }}

